-- AlterTable
ALTER TABLE `companysetting` ADD COLUMN `avoirPrefix` VARCHAR(191) NOT NULL DEFAULT 'AC',
    ADD COLUMN `avoirStartNumber` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `commandePrefix` VARCHAR(191) NOT NULL DEFAULT 'CC',
    ADD COLUMN `commandeStartNumber` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `devisPrefix` VARCHAR(191) NOT NULL DEFAULT 'DV',
    ADD COLUMN `devisStartNumber` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `invoicePrefix` VARCHAR(191) NOT NULL DEFAULT 'FC',
    ADD COLUMN `invoiceStartNumber` INTEGER NOT NULL DEFAULT 1;
