-- AlterTable CommandeClient: Add source column and change statut type
ALTER TABLE `CommandeClient` 
  ADD COLUMN `source` ENUM('WEBSITE', 'FACEBOOK', 'INSTAGRAM', 'WHATSAPP', 'PHONE', 'OTHER') NOT NULL DEFAULT 'OTHER',
  MODIFY `statut` ENUM('EN_ATTENTE_VALIDATION', 'ANNULE', 'EN_COURS_PREPARATION', 'EN_COURS_LIVRAISON', 'LIVRE') NOT NULL DEFAULT 'EN_ATTENTE_VALIDATION';
