-- AlterTable
ALTER TABLE `avoirclient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `boncommandeclient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `bondecommande` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `bondereception` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `bonlivraisonclient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `devis` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `devisclient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `factureavoir` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `factureclient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `facturefournisseur` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';
