-- AlterTable
ALTER TABLE `AvoirClient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `BonCommandeClient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `BonDeCommande` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `BonDeReception` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `BonLivraisonClient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `Devis` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `DevisClient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `FactureAvoir` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `FactureClient` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';

-- AlterTable
ALTER TABLE `FactureFournisseur` MODIFY `statut` ENUM('BROUILLON', 'ENVOYE', 'ACCEPTE', 'REFUSE', 'ANNULE', 'TRAITE', 'LIVRE', 'PAYE') NOT NULL DEFAULT 'BROUILLON';
